### ISSUE TITLE
Was there a bug in continuous shooting mode?

### ISSUE THREAD

**Issue by darkeroticism** [ShinyColorsDB/ShinyColorsDB-SpineViewer#11]
@alex94539 
Hi. As far as I can see from [this commit](https://github.com/ShinyColorsDB/ShinyColorsDB-SpineViewer/commit/0e7eeb3742cffc83938f21ee5b8ec032cf50040e), was there a problem with continuous shooting mode?
It seems that this is due to the severe pollution of `async`...

**Comment by alex94539** [comment]
Oof

I'll dig into it next week

I'm now in tokyo and have no pc for work 🫠

**Comment by alex94539** [comment]
Oof

I'll dig into it next week

I'm now in tokyo and have no pc for work 🫠

I'v rolled back to previous commit temporarily

**Comment by darkeroticism** [comment]
Ah, you're coming to Yokohama.😁
I modified Pixi.js without knowing much about it, so I feel responsible if a bug occurs.

**Comment by alex94539** [comment]
should be fixed, I'll close this issue by friday
