### ISSUE TITLE
character missing in spine viewer

### ISSUE THREAD

**Issue by vkt133** [ShinyColorsDB/ShinyColorsDB-SpineViewer#14]
when i chose akane（黒川あかね） it didnt look like her own combolist for skin showed up... is it just missing or something?

**Comment by alex94539** [comment]
not updated yet, lol
I'm busy for my master thesis recently, so maybe next month?

**Comment by vkt133** [comment]
i see... well once you added her will you let me know here?

**Comment by alex94539** [comment]
@vkt133 should be fixed...?

**Comment by vkt133** [comment]
yea, thanks! its fixed now... srry if the request caused some inconvenience for you, @alex94539
