### ISSUE TITLE
Is it able to save spine without losing alpha channel?

### ISSUE THREAD

**Issue by Hydrogen5** [ShinyColorsDB/ShinyColorsDB-SpineViewer#4]
I want to get pictures with alpha channel but idk what should i do. 
![image](https://github.com/ShinyColorsDB/ShinyColorsDB-SpineViewer/assets/32235220/09c92882-092f-49ad-88b2-44b9d4026e7f)
Should i set background to transparent?

**Comment by alex94539** [comment]
try this
[https://mspine.shinycolors.moe](https://mspin.shinycolors.moe/)

**Comment by Hydrogen5** [comment]
> try this [https://mspine.shinycolors.moe](https://mspine.shinycolors.moe/)

thanks!
