### ISSUE TITLE
noctchill and SHHis members don't have "イノセントセーラー(innocent sailor)" dress.

### ISSUE THREAD

**Issue by darkeroticism** [ShinyColorsDB/ShinyColorsDB-SpineViewer#5]
Hi. I was surprised to find a Spine emulator for Shiny Colors.
Not only card illustrations but also standing pictures and animations are attractive.
Sending you big respect from Japan.
I have no knowledge of Spine or Pixi.JS, but I really wanted to download it as an image file, so I used Developer Tools to analyze various things and access the API, but please forgive me. 😁

Now to get to the point, "イノセントセーラー(Innocent Sailor)" is displayed in the "dresses" pull-down menu of members of noctchill and SHHis, but it should not have actually been implemented.
Please fix it when you have free time.

**Comment by alex94539** [comment]
ShinyColorsDB/ShinyColorsDB-ApiServer#f2866a4d3a92f44806c259ee8a9d94921dac86fb
fix backend dumping not exist record
