### ISSUE TITLE
Nanakusa Hazuki's Tachie Cannot be correctly loaded.

### ISSUE THREAD

**Issue by MarcusDaskalos** [ShinyColorsDB/ShinyColorsDB-SpineViewer#6]
I don't know why, but only Hazuki-san's Tachie cannot be loaded. When I choose Hazuki-san, it just show me a blank window.

**Comment by alex94539** [comment]
S3 path issue, give me few hours

**Comment by alex94539** [comment]
should be fixed, clear your browser cache if anything is not working @MarcusDaskalos .
