### ISSUE TITLE
Do you accept PR?

### ISSUE THREAD

**Issue by darkeroticism** [ShinyColorsDB/ShinyColorsDB-SpineViewer#7]
@alex94539 
Hello. 
I like ShinyColors' standing pictures and would like to save them as images, so I modified `main.js` a little using the local overrides on the Chrome Developer Tool to make it easier to save.
If possible, I would like to formally submit a PR, but are you willing to accept?

**Comment by alex94539** [comment]
Of course you can submit a PR. I'll decide to accept or not depends on the context you submit.
BTW "save as images" is already available on https://mspine.shinycolors.moe, maybe you'd like to try it out(?

**Comment by darkeroticism** [comment]
Oh, I always used https://spine.shinycolors.moe/ .
Are there any differences other than the image save button?

My custom has the following four points, 

- Add image save button
- Strict file name to save(example: "桑山千雪-Anniversary-【オーバーキャストモノクローム】桑山千雪-一般_演出服.png" )
- Automatically save images when switching  characters, costumes, and types.(It was quite convenient, but I don't make a on/off switch yet.) 
- Disable the animation that was set to `wait` when changing characters, costumes, and types.(This is more convenient when saving a large number of standing pictures.)

and I was trying to issue a PR for the first two.
